# Generated by Django 5.2 on 2025-05-01 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default=datetime.datetime(2025, 5, 1, 15, 10, 48, 586087, tzinfo=datetime.timezone.utc), upload_to='course/'),
            preserve_default=False,
        ),
    ]
