# Generated by Django 5.2 on 2025-05-01 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_bob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='sulg',
            new_name='slug',
        ),
    ]
