# Generated by Django 5.2 on 2025-05-01 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_rename_sulg_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bob',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bob', to='course.course'),
        ),
    ]
