# Generated by Django 5.2 on 2025-05-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_bob_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bob',
            name='icone',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
